# Generated by Django 3.0.2 on 2020-02-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ff', '0002_auto_20200215_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoe',
            old_name='typeName',
            new_name='productType',
        ),
    ]
