# Generated by Django 3.0.2 on 2020-02-15 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff', '0003_auto_20200215_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='productType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ff.ProductType'),
        ),
    ]
