# Generated by Django 3.0.2 on 2020-02-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff', '0004_auto_20200215_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.AddField(
            model_name='shoe',
            name='usSize10_0',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='usSize10_5',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='usSize11_0',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='usSize11_5',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='usSize12_0',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='usSize8_0',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='usSize8_5',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='usSize9_0',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoe',
            name='usSize9_5',
            field=models.BooleanField(default=True),
        ),
    ]
