# Generated by Django 3.0.2 on 2020-02-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff', '0005_auto_20200215_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(default='Brandless', max_length=80),
        ),
    ]
