# Generated by Django 3.0.2 on 2020-02-15 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ff', '0007_shoe_qtyin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='productType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoeptype', to='ff.ProductType'),
        ),
        migrations.CreateModel(
            name='Skirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shoe Type', max_length=150, unique=True)),
                ('brand', models.CharField(default='Brandless', max_length=80)),
                ('desc', models.TextField(max_length=400)),
                ('thumbnail1', models.ImageField(default='default-thumbnail-shoes.png', upload_to='thumbnails/shoes')),
                ('thumbnail2', models.ImageField(default='default-thumbnail-shoes.png', upload_to='thumbnails/shoes')),
                ('thumbnail3', models.ImageField(default='default-thumbnail-shoes.png', upload_to='thumbnails/shoes')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skirtptype', to='ff.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='Bag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shoe Type', max_length=150, unique=True)),
                ('brand', models.CharField(default='Brandless', max_length=80)),
                ('desc', models.TextField(max_length=400)),
                ('thumbnail1', models.ImageField(default='default-thumbnail-shoes.png', upload_to='thumbnails/shoes')),
                ('thumbnail2', models.ImageField(default='default-thumbnail-shoes.png', upload_to='thumbnails/shoes')),
                ('thumbnail3', models.ImageField(default='default-thumbnail-shoes.png', upload_to='thumbnails/shoes')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bagptype', to='ff.ProductType')),
            ],
        ),
    ]
