# Generated by Django 3.0.2 on 2020-02-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ff', '0009_auto_20200216_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='retailPrice',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skirt',
            name='retailPrice',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
